version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DB_HOST=mysqlHost
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqlHost:3306/${MYSQL_DATABASE}
    command: ["./wait-for-it.sh", "mysqlHost:3306", "--", "npm", "start"]
    volumes:
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh:ro
    depends_on:
      - mysqlHost
      - migrate

  migrate:
    build:
      context: .
      dockerfile: dockerfile
    command: ["./wait-for-it.sh", "mysqlHost:3306", "--", "npx", "prisma", "migrate", "deploy"]
    volumes:
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh:ro
    depends_on:
      - mysqlHost
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqlHost:3306/${MYSQL_DATABASE}

  nginx:  
    image: nginx:latest  
    ports:
      - "${PORT}:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.template:/etc/nginx/conf.d/default.template:ro
    command: /bin/sh -c "envsubst '$$PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - PORT=${PORT}

  mysqlHost:
    image: mysql:8.0
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: libraryDb_docker

volumes:
  db_data:
